# Eat Safe, Love

## Notebook Set Up

In [20]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint

In [21]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [22]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [23]:
# review the collections in our database
print(db.list_collection_names())

['establishments']

In [24]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [25]:
# Find the establishments with a hygiene score of 20
query = {"scores.Hygiene": {"$gt": 20}}


# Use count_documents to display the number of documents in the result
results=establishments.count_documents(query)
print(results)

# Display the first document in the results using pprint
establishments.find_one(query)

7

{'_id': ObjectId('6461130c6fd0f653bea5da6e'),
 'FHRSID': 1349147,
 'ChangesByServerID': 0,
 'LocalAuthorityBusinessID': '21/00036/COM',
 'BusinessName': 'Inferno',
 'BusinessType': 'Takeaway/sandwich shop',
 'BusinessTypeID': 7844,
 'AddressLine1': 'Skyline Hotel',
 'AddressLine2': 'Chelmsford Road',
 'AddressLine3': 'Barnston',
 'AddressLine4': 'Dunmow',
 'PostCode': 'CM6 1LP',
 'Phone': '',
 'RatingValue': '0',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingDate': '2022-01-27T00:00:00',
 'LocalAuthorityCode': '122',
 'LocalAuthorityName': 'Uttlesford',
 'LocalAuthorityWebSite': 'http://www.uttlesford.gov.uk',
 'LocalAuthorityEmailAddress': 'environmentalhealth@uttlesford.gov.uk',
 'scores': {'Hygiene': 25, 'Structural': 20, 'ConfidenceInManagement': 20},
 'SchemeType': 'FHRS',
 'geocode': {'longitude': '0.383023', 'latitude': '51.85643'},
 'RightToReply': '',
 'Distance': 4650.02974294374,
 'NewRatingPending': False,
 'meta': {'dataSource': None,
  'extractDate': '0001-01-01T00:00:00',
  'itemCount': 0,
  'returncode': None,
  'totalCount': 0,
  'totalPages': 0,
  'pageSize': 0,
  'pageNumber': 0},
 'links': [{'rel': 'self',
   'href': 'http://api.ratings.food.gov.uk/establishments/1349147'}]}

In [26]:
import pandas as pd
# Convert the result to a Pandas DataFrame
hygiene_results = list(establishments.find(query))
hygiene_df = pd.DataFrame(hygiene_results)

# Display the number of rows in the DataFrame
print(hygiene_df.shape[0])

# Display the first 10 rows of the DataFrame
hygiene_df.head(10)

7

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,6461130c6fd0f653bea5da6e,1349147,0,21/00036/COM,Inferno,Takeaway/sandwich shop,7844,Skyline Hotel,Chelmsford Road,Barnston,...,http://www.uttlesford.gov.uk,environmentalhealth@uttlesford.gov.uk,"{'Hygiene': 25, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': '0.383023', 'latitude': '51.85643'}",,4650.029743,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
1,6461130c6fd0f653bea5e4a9,785554,0,08/00054/FOOD,Stratford News And Wines,Retailers - other,4613,107 Romford Road,Stratford,London,...,https://www.newham.gov.uk,food@newham.gov.uk,"{'Hygiene': 25, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': '0.008382', 'latitude': '51.5427...",,4652.047527,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
2,6461130c6fd0f653bea5e658,514156,0,147,The Plough & Harrow,Pub/bar/nightclub,7843,,419 High Road Leytonstone,,...,http://www.walthamforest.gov.uk,environmentalhealth@walthamforest.gov.uk,"{'Hygiene': 25, 'Structural': 25, 'ConfidenceI...",FHRS,"{'longitude': '0.006434', 'latitude': '51.5581...",,4652.681025,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
3,6461130c6fd0f653bea5e665,514651,0,47178,Chicks,Takeaway/sandwich shop,7844,,497 High Road,,...,http://www.walthamforest.gov.uk,environmentalhealth@walthamforest.gov.uk,"{'Hygiene': 25, 'Structural': 25, 'ConfidenceI...",FHRS,"{'longitude': '0.0071334', 'latitude': '51.559...",,4652.699935,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
4,6461130c6fd0f653bea5e69d,514221,0,17220,The Continental Food Exchange/TFC Leytonstone,Retailers - other,4613,,647-661 High Road Leytonstone,,...,http://www.walthamforest.gov.uk,environmentalhealth@walthamforest.gov.uk,"{'Hygiene': 25, 'Structural': 25, 'ConfidenceI...",FHRS,"{'longitude': '0.009602', 'latitude': '51.5639...",,4652.776654,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
5,6461130c6fd0f653bea5e6e0,552296,0,63877,O42,Restaurant/Cafe/Canteen,1,,885 High Road Leytonstone,,...,http://www.walthamforest.gov.uk,environmentalhealth@walthamforest.gov.uk,"{'Hygiene': 25, 'Structural': 25, 'ConfidenceI...",FHRS,"{'longitude': '0.014137', 'latitude': '51.5708...",,4652.865838,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
6,6461130c6fd0f653bea5e85e,1351355,0,348976,Busy Bees at Leytonstone,Caring Premises,5,Whipps Cross University Hospital,Whipps Cross Road,,...,http://www.walthamforest.gov.uk,environmentalhealth@walthamforest.gov.uk,"{'Hygiene': 25, 'Structural': 25, 'ConfidenceI...",FHRS,"{'longitude': '0.0034702', 'latitude': '51.577...",,4653.495442,True,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [37]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = establishments.aggregate([{"$match": {"AddressLine3": "London", "RatingValue": {"$gte": 4}}}])

# Use count_documents to display the number of documents in the result
results=establishments.count_documents(query)
# print(results)

# # Display the first document in the results using pprint
# establishments.find_one(query)

InvalidDocument: cannot encode object: <pymongo.command_cursor.CommandCursor object at 0x7fc3e2750b80>, of type: <class 'pymongo.command_cursor.CommandCursor'>

In [ ]:
# Convert the result to a Pandas DataFrame

# Display the number of rows in the DataFrame

# Display the first 10 rows of the DataFrame

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [60]:
# query = { "BusinessName": "Penang Flavours" }
# update = { '$set': { "geocode.latitude": 51.4925572, "geocode.longitude": 0.0448072} }
# establishments.update_one(query, update)


# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
latitude =  51.4925572
longitude = 0.0448072

query = {
    "geocode.latitude": {"$gt": latitude - degree_search, "$lt": latitude + degree_search},
    "geocode.longitude": {"$gt": longitude - degree_search, "$lt": longitude + degree_search},
    "RatingValue": 5
    
}
sort = [("scores.Hygiene", 1)]

# Find and print the matching documents
results = list(establishments.find(query).sort(sort))
pprint(results)

[]

In [61]:
# Convert result to Pandas DataFrame

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [46]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
# 2. Groups the matches by Local Authority
# 3. Sorts the matches from highest to lowest
pipeline = [
    {"$match": {"scores.Hygiene": 0}},
    {"$group": {"_id": "$LocalAuthorityName", "count": {"$sum": 1}}},
    {"$sort": {"count": -1}}
]

# Print the first 10 results

cursor = establishments.aggregate(pipeline)
for i, result in enumerate(cursor):
    pprint(result)
    if i >= 9:
        break

{'_id': 'Thanet', 'count': 1130}
{'_id': 'Greenwich', 'count': 882}
{'_id': 'Maidstone', 'count': 713}
{'_id': 'Newham', 'count': 711}
{'_id': 'Swale', 'count': 686}
{'_id': 'Chelmsford', 'count': 680}
{'_id': 'Medway', 'count': 672}
{'_id': 'Bexley', 'count': 607}
{'_id': 'Southend-On-Sea', 'count': 586}
{'_id': 'Tendring', 'count': 542}

In [48]:

# Convert the result to a Pandas DataFrame
df = pd.DataFrame(list(establishments.aggregate(pipeline)))

# Display the number of rows in the DataFrame
print(df.shape[0])

# Display the first 10 rows of the DataFrame
df.head(10)

55

               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542